### ISSUE TITLE
Re-enable Capistrano 3 support

### ISSUE THREAD

**Issue by sandfox-im** [rvm/rvm-capistrano#114]
It seems that cap3 support was disabled after 1.5.0:
https://github.com/rvm/rvm-capistrano/commit/431170436402a0e27abb35003d3ae58dd5d8152b

cap3 has been released for quite a while now and 1.5.0 works perfectly with it
the support should be re-enabled in gemspec

**Comment by mpapis** [comment]
capistrano3 is not compatible with capistrano2 - please use https://github.com/rvm/rvm1-capistrano3 instead
